
SECRET_KEY: 'flask'
DEBUG: True

SQLALCHEMY_COMMIT_ON_TEARDOWN: True
SQLALCHEMY_DATABASE_URI: 'mysql+pymysql://root:Qw123456@localhost:3306/website?charset=utf8mb4'
SQLALCHEMY_TRACK_MODIFICATIONS: True
SQLALCHEMY_POOL_SIZE: 10
SQLALCHEMY_MAX_OVERFLOW: 10

AWS_ACCESS_KEY_ID: 'PDS85XLJFTNF66JEA8SF'
AWS_SECRET_ACCESS_KEY: 'XcJV4NFJJNw8NmjVYCRF5omtG1F5A0hz2uPTvYIW'
AWS_ENDPOINT_URL: 'http://www.baidu.com'
AWS_BUCKET_NAME: 'datasource'
AWS_ALLOWED_EXTENSIONS: None

REDIS_URL: 'http://www.baidu.com'
SESSION_USE_SIGNER: True
SESSION_TYPE: 'redis'
CACHE_CLOUD_URL: 'http://www.baidu.com'
SESSION_KEY_PREFIX: 'session:'
PERMANENT_SESSION_LIFETIME: 7200
